### ISSUE TITLE
psalm not running on command line

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-cycle#216]
### What do you get instead? Uncaught RuntimeException: PHP Error: require(C:\wamp128\www\yii-cycle\vendor\composer/../../tests/bootstrap.php): Failed to open stream: No such file or directory in C:\wamp128\www\yii-cycle\vendor\composer\autoload_real.php:41 for command with CLI args "./vendor/bin/psalm" in C:\wamp128\www\yii-cycle\vendor\vimeo\psalm\src\Psalm\Internal\ErrorHandler.php:75
Stack trace:
#0 C:\wamp128\www\yii-cycle\vendor\composer\autoload_real.php(41): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'require(C:\\wamp...', 'C:\\wamp128\\www\\...', 41)
#1 C:\wamp128\www\yii-cycle\vendor\composer\autoload_real.php(41): require()
#2 C:\wamp128\www\yii-cycle\vendor\composer\autoload_real.php(45): {closure}('cb57751dcd3be24...', 'C:\\wamp128\\www\\...')
#3 C:\wamp128\www\yii-cycle\vendor\autoload.php(25): ComposerAutoloaderInit95bc757acfaf11632b5dc06f47d31ec7::getLoader()
#4 C:\wamp128\www\yii-cycle\vendor\vimeo\psalm\src\Psalm\Internal\CliUtils.php(132): require_once('C:\\wamp128\\www\\...')
#5 C:\wamp128\www\yii-cycle\vendor\vimeo\psalm\src\Psalm\Internal\Cli\Psalm.php(234): Psalm\Internal\CliUtils::requireAutoloaders('C:\\wamp128\\www\\...', false, 'vendor')
#6 C:\wamp128\www\yii-cycle\vendor\vimeo\psalm\src\Psalm\Internal\IncludeCollector.php(35): Psalm\Internal\Cli\Psalm::Psalm\Internal\Cli\{closure}()
#7 C:\wamp128\www\yii-cycle\vendor\vimeo\psalm\src\Psalm\Internal\Cli\Psalm.php(230): Psalm\Internal\IncludeCollector->runAndCollect(Object(Closure))
#8 C:\wamp128\www\yii-cycle\vendor\vimeo\psalm\psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#9 C:\wamp128\www\yii-cycle\vendor\bin\psalm(119): include('C:\\wamp128\\www\\...')
#10 {main}
(Psalm (unknown version) crashed due to an uncaught Throwable)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.3
| Operating system | Windows 11

**Comment by rossaddison** [comment]
I have reforked and psalm running fine under php8.1. I think this is a php 8.3 issue with regards to the use of constants and can be easily fixed by e.g. making sure types e.g strings, arrays, etc are declared with constants. i.e.
